### ISSUE TITLE
Error during installation - 404 Not Found for scrypted-serve

### ISSUE THREAD

**Issue by jordanmkoncz** [aegjoyce/ha-addons#16] opened 2022-09-09 23:12 UTC
I'm trying to get Scrypted up and running on my Raspberry Pi 4 running HAOS. I got up to this part of the installation instructions:

> Scrypted will then be accessible via [YOUR_HOME_ASSISTANT_ADDRESS]:10443 - check the add-on logs after clicking 'Start' to confirm the server address.

This URL fails to load. When I go to the Log tab of the add-on, I see the following:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/scrypted-serve - Not found
npm ERR! 404 
npm ERR! 404  'scrypted-serve@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-09T22_37_40_934Z-debug-0.log
```

Any ideas on what's going on here?

**Comment by DuncanRae** [comment] 2022-09-10 06:29
I’m getting the same error after upgrading to latest version.

**Comment by martindinicolino** [comment] 2022-09-10 12:01
> I’m getting the same error after upgrading to latest version.
> 
> Addon won’t start. Rolled back and working fine again.

same here

**Comment by flame4ever** [comment] 2022-09-10 12:07
same here

**Comment by flame4ever** [comment] 2022-09-10 12:09
> I’m getting the same error after upgrading to latest version.
> 
> Addon won’t start. Rolled back and working fine again.

same here

**Comment by streets97f** [comment] 2022-09-10 17:54
any fix on this?

**Comment by aegjoyce** [comment] 2022-09-10 19:16
No imminent fix as I have a full time job and my work schedule doesn’t permit me time at the moment. Will look when I can.

**Comment by streets97f** [comment] 2022-09-10 21:12
sorry didn’t mean to bug you, I understand…I’m working this weekend too. I fiddled with it a bit this morning but didn’t get anywhere. Hopefully it won’t be a big issues to fix when you get a chance to look at it. Thanks

**Comment by DrPepperFueled** [comment] 2022-09-11 00:26
looks like maybe a typographical error (its missing the last r in the 'https://registry.npmjs.org/scrypted-serve' URI?)

**Comment by blakekirven** [comment] 2022-09-11 14:14
how do you roll back to a previous version? sorry if that's dumb... I appreciate any help

**Comment by DrPepperFueled** [comment] 2022-09-11 14:45
Use the restore function in Home Assistant (system/backups/select the backup taken when installing addon, choose restore)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hiddevanbrussel** [comment] 2022-09-11 20:52
Had same issue after installing v0.2.5. Reroll to 0.2.2 does the trick.

**Comment by cristian199612** [comment] 2022-09-12 14:21
Is it possible to reroll without a backup?

**Comment by streets97f** [comment] 2022-09-13 04:11
I was able to get the latest version loaded and working. If you have the Portainer addon installed in your Home Assistant, you can pull the latest docker image and it runs fine on the most updated version. I think there maybe something wrong with v0.2.5 image and koush has updated the latest image even though it stills states v0.2.5.

Log out of the Scrypted UI, if you have it up and running
Update the Scrypted addon to v0.2.5 in HA
Go to Portainer, login, and select containers.
Click on the scrypted container, and select the duplicate/edit button
In the Image search box enter: koush/scrypted:latest
scroll down and click deploy container and select "replace" when prompted
the latest image will pull and the container should restart, if not click start on the top
scroll down and select you preferred restart policy and click update

Now, if you stop or restart Scrypted via the Home Assistant addon, then the addon will pull the original v0.2.5 and it'll break again. But you can still restart HA and Scrypted from with in the UI and work fine. If the restart policy is set in portainer, it should automatically restart with the working version if it crashes.

**Comment by aegjoyce** [comment] 2022-09-13 13:39
Also causing issues on other installations: https://github.com/koush/scrypted/issues/373#issue-1370030922

I've temporarily changed this to pull the latest image, you should see this as an update in the add-on store, could you test to see if this fixes the problem as per https://github.com/aegjoyce/ha-addons/issues/16#issuecomment-1244873330

Looks like Koush is aware of this, I will manually update to the next image when it is released and hopefully it won't cause the same palaver

**Comment by Daneish** [comment] 2022-09-13 14:16
I initially had the same issue with `0.2.5` then rolled back to `0.2.2`. I’ve now updated to `latest` and all is working. I also confirmed that I’m running 0.2.5 from within the Scrypted console.

Thanks for the fix and for maintaining this add on!

**Comment by DrPepperFueled** [comment] 2022-09-13 14:49
I have also just completed updating the addon to latest release and appears to be working well.

thanks for the effort to get this back up and running!

**Comment by koush** [comment] 2022-09-14 04:55
> Also causing issues on other installations: [koush/scrypted#373 (comment)](https://github.com/koush/scrypted/issues/373#issue-1370030922)

This is not the same issue. The linked bug is a Mac install error, and this is a docker run problem. The install has already completed in the docker image on the build server.s

**Comment by koush** [comment] 2022-09-14 05:07
might be fixed with this https://github.com/koush/scrypted/commit/c010f5a88d3ec88a2b55e22289918aaf076cf403

**Comment by koush** [comment] 2022-09-14 05:08
0.2.8 is rolling out. please check that.

**Comment by aegjoyce** [comment] 2022-09-14 19:57
Bumped to 0.2.8 for testing

**Comment by Daneish** [comment] 2022-09-18 14:55
I was waiting for Home Assistant to generate a notification that an update was available. It didn’t come and the update.scrypted_update entity was unavailable (maybe had issues comparing `latest` with `0.2.8`?), but browsing to Settings > Add-ons > Scrypted allowed me to update it.

I can confirm everything is all still working with 0.2.8. Cheers!

**Comment by aegjoyce** [comment] 2022-09-18 15:36
Excellent - will close this for now but can reopen if issues remain. Thanks @koush for the fix

**Closed by aegjoyce** 2022-09-18 15:36 UTC
